language: ruby
rvm:
  - 2.4.1

before_install:
  - nvm install node

install:
  - bundle install --path vendor
  - npm install

before_script:
 - chmod +x ./cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - npm run print
  - ./cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - netlify-cms     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: true
