baseURL: /
languageCode: en-us
title: Thomas Azar
frontmatter:
  date:
    - ":filename"
    - ":default"
sectionPagesMenu: "main"
menu:
  main:
    - identifier: news
      title: News
      name: News
      url: /#news
      weight: 10
    - identifier: writings
      title: Writings
      name: Writings
      url: /writings/
      weight: 40
    - identifier: media
      title: Media
      name: Media
      url: /media/
      weight: 30
params:
  matomoid: 1
