title: Thomas Azar
description: Official website of actor Thomas Azar.
params:
  id: 1
  date_updated: '2021-03-28T13:48:35Z'
  assets_url: http://192.168.163.5:8055/assets
  splash_image: 48f9aa21-49e7-4269-a98a-5a501b1e3887
