[Settings]
  ID = "26304c5f-909b-444a-9a4c-b8bacfece441"

[build]
  Base = ""
  Publish = "public"
  Command = "hugo --gc --minify -e production"
  environment = { HUGO_VERSION = "0.88.1" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' https://res.cloudinary.com; style-src 'self'; base-uri 'self'; form-action 'self'; font-src 'self'; object-src https://res.cloudinary.com"