backend:
  name: git-gateway
  branch: netlify-cms
media_folder: "content/uploads"
public_folder: "/uploads"
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - label: "Footer"
        name: "footer"
        widget: "object"
        fields:
          - {label: "Where", name: "where", widget: "markdown"}
          - {label: "When", name: "when", widget: "markdown"}
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Director", name: "director", widget: "string"}
          - {label: "Featuring", name: "featuring", widget: "string"}