backend:
  name: bitbucket
  repo: design_by_thomas_azar/thomasazar.net # Path to your Bitbucket repository
  branch: netlify-cms
media_folder: "/images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "writings" # Used in routes, e.g., /admin/collections/blog
    label: "Writings" # Used in the UI
    label_singular: "Post"
    folder: "writings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
