---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/resume.md
  label: Resume
  match: "**/*"
- type: document
  path: content/_index.md
  label: Home
- type: document
  path: content/blurb.md
  label: Blurb
- type: directory
  path: content/news
  label: News
  create: documents
  match: "**/*"
  exclude: _index.md
- type: directory
  path: content/media
  label: Media
  create: documents
  match: "**/*"
  templates:
  - media-page
- type: directory
  path: content/writings
  label: Writings
  create: documents
  match: "**/*"
  templates:
  - blog-post
upload_dir: thomasazar.net
public_path: https://res.cloudinary.com/thomasazar/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
