name: Build from Directus

on:
  push:
    branches:
      - build  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        env:
          HUGO_API_AUTH_URL: ${{ secrets.HUGO_API_AUTH_URL }}
          HUGO_GQL_API_URL: ${{ secrets.HUGO_GQL_API_URL }}
          HUGO_API_GQL_USER: ${{ secrets.HUGO_API_GQL_USER }}
          HUGO_API_GQL_PASSWORD: ${{ secrets.HUGO_API_GQL_PASSWORD }}
        run: hugo --environment build 

      - name: Clear old content
        run: rm -r content
      - name: Copy new content
        run: mv tmpContent -t content

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
